os: linux
dist: xenial
language: ruby
cache: bundler
env:
  - BUNDLE_WITHOUT="production development"
before_script: bin/setup
script: bin/ci
services:
  - postgresql
notifications:
  slack:
    rooms:
      - secure: A2U1yGwdkRCqimsBAUFFVxfqg0EqNEFHkQWLWpRcv5re4wJWKaDeZy2TAC50Ig+k+03ee3bEFs9ldgqvrj/ndPijqPShQq0vxKRTIVmVpyYB5iPLilI8bfgJPdBElvU12pEiIOs4fRegq3Xq3Gq/rMht/o2lBJEeJQFj3SP3nrg=
    on_success: change
    on_failure: always
  email: false
